name: aiplayer
description: "universal media player"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.3.10
  dio: ^5.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.4.0
  get: ^4.7.2

  shared_preferences: ^2.0.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
